### ISSUE TITLE
Signing html body content 

### ISSUE THREAD

**Issue by dwllnet** [toorop/go-dkim#3]
When signing an email with html content, dkim will not verify with  dkim=neutral (body hash did not verify). Switch body content to simple text, dkim will verify. 

Any ideas?

**Comment by toorop** [comment]
Could you provide your options and your email sample ?

**Comment by dwllnet** [comment]
header := `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
                          <html xmlns="http://www.w3.org/1999/xhtml">
                          <head>
                          <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                          <body>`
footer := `</body></html>`
htmlFull := header + footer
bodyLen := len(htmlFull)
options := dkim.NewSigOptions()
options.PrivateKey = []byte(privateKey)
options.Domain = domain
options.Selector = selector
options.SignatureExpireIn = 3600
options.BodyLength = uint(bodyLen)
options.Headers = []string{"From","To","Subject"}
options.AddSignatureTimestamp = true
options.Canonicalization = "simple/simple"
options.QueryMethods = []string{"dns"}

**Comment by dwllnet** [comment]
Additional  information, if header is a single line, no line feed, then body passes.

**Comment by toorop** [comment]
Hum what are you trying to do ?
header is relative to email headers not html "head" part. And more genaraly you sign an email not an HTML doc/part.
See: http://www.dkim.org/ for more info about DKIM

**Comment by dwllnet** [comment]
Trying to send an email with HTML content

**Comment by toorop** [comment]
So sign the mail not the html part. See example on main page.

**Comment by dwllnet** [comment]
Am thinking that's what am doing, 

msg := []byte(qTo + qReturnPath + qFrom + qMimeVersion + qContentType + qSubject + "\r\n" + htmlFull)
  errDkim := dkim.Sign(&msg, options)

   if errDkim != nil {
           fmt.Println("DKIM error")
           log.Fatal(errDkim)
                }

**Comment by toorop** [comment]
it's not what you have done with:
header := <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <body>
footer := </body></html>
htmlFull := header + footer
bodyLen := len(htmlFull)

And i don't know if it is what you do with:
msg := []byte(qTo + qReturnPath + qFrom + qMimeVersion + qContentType + qSubject + "\r\n" + htmlFull)
errDkim := dkim.Sign(&msg, options)

init msg with a plain mail not with var otherwise i can't help you. I must be able to run your code with your mail

**Comment by dwllnet** [comment]
Am not following you on, init msg with a plain mail, here is he full example code.

auth := smtp.PlainAuth("","foo","testing",127.0.0.1,)

header := `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	  <html xmlns="http://www.w3.org/1999/xhtml">
	  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	  <body>`

footer := `</body></html>`

htmlDocument := header  + footer
 
bodyLen := len(htmlDocument)

options := dkim.NewSigOptions()
options.PrivateKey = []byte(privateKey)
options.Domain = domain
options.Selector = selector
options.SignatureExpireIn = 3600
options.BodyLength = uint(bodyLen)
options.Headers = []string{"From","To","Subject"}
options.AddSignatureTimestamp = true
options.Canonicalization = "simple/simple"
options.QueryMethods = []string{"dns"}

qTo := "To: foo@example.com\r\n"
qReturnPath := "Return-Path: bar@example.com\r\n"
qFrom := "From: bar@example.com\r\n"
qMimeVersion := "MIME-Version: 1.0\r\n"
qContentType := "Content-Type: text/html; charset=UTF-8\r\n"
qSubject := "Subject: " + subject + "\r\n"

email := []byte(qTo + qReturnPath + qFrom + qMimeVersion + qContentType + qSubject + "\r\n" + htmlDocument)

errDkim := dkim.Sign(&email, options)

if errDkim != nil {
	fmt.Println("DKIM error")
	log.Fatal(errDkim)
}

smtpError := smtp.SendMail("localhost:25", auth, "bar@example.com", "foo@example.com", email)
if smtpError != nil {
	log.Fatal(strings.Split(smtpError.Error(), "\n"))
}
